version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  initdb:
    image: ${AIRFLOW_IMAGE}
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: airflow db init

  webserver:
    image: ${AIRFLOW_IMAGE}
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - initdb
    volumes:
      - ./dags:/opt/airflow/dags
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8080:8080"
    entrypoint: /entrypoint.sh
    command: airflow webserver --port 8080

  scheduler:
    image: ${AIRFLOW_IMAGE}
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - initdb
    volumes:
      - ./dags:/opt/airflow/dags
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: airflow scheduler

volumes:
  postgres-data: