name: Build and Test Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: podcast_asr:latest

    - name: Run container and test
      run: |
        docker run --name my-container -d -p 8080:80 podcast_asr:latest
        sleep 10
        curl http://localhost:8080
        docker stop my-container